/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker-env.d.ts` (hash: 13a4e2882c3dc5edb561445d5d376776)
interface __BaseEnv_Env {
	STATUS: KVNamespace;
	ASSETS: Fetcher;
	SITE_ID: "example-site";
	TARGET_URL: "https://example.com/";
	COMPONENT_SLUG: "website";
	COMPONENT_NAME: "Website";
	COMPONENT_GROUP: "Website";
	SHOW_LATENCY: "true";
	POLL_INTERVAL_SECONDS: "60";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_ID" | "TARGET_URL" | "COMPONENT_SLUG" | "COMPONENT_NAME" | "COMPONENT_GROUP" | "SHOW_LATENCY" | "POLL_INTERVAL_SECONDS">> {}
}
